---
version: 1
env:
  SWIFTCHECK_MAX_TESTS: 100000  # Extreme iterations for nightly runs
  SWIFTCHECK_MAX_SIZE: 2000
  SWIFTCHECK_MAX_DISCARD_RATIO: 10
name: Nightly Stress Testing
trigger:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
      branches:
        - main
        - develop
    - cron: '0 12 * * *'  # Daily at noon UTC
      branches:
        - main
        - develop
actions:
  - name: Marathon Property Tests - Device 1
    platform: iOS
    runtime:
      version: '17.0'
      device: 'iPhone 15 Pro Max'
    scheme: FaithQuest
    test-plan: Default
    test-repetitions: 20
    actions:
      - test
    environment:
      xcode: latest
      
  - name: Marathon Property Tests - Device 2
    platform: iOS
    runtime:
      version: '17.0'
      device: 'iPhone 15 Pro'
    scheme: FaithQuest
    test-plan: Default
    test-repetitions: 20
    actions:
      - test
    environment:
      xcode: latest
      
  - name: Marathon Property Tests - Device 3
    platform: iOS
    runtime:
      version: '17.0'
      device: 'iPhone 15'
    scheme: FaithQuest
    test-plan: Default
    test-repetitions: 20
    actions:
      - test
    environment:
      xcode: latest
      
  - name: Marathon Property Tests - Device 4
    platform: iOS
    runtime:
      version: '17.0'
      device: 'iPad Pro (12.9-inch)'
    scheme: FaithQuest
    test-plan: Default
    test-repetitions: 20
    actions:
      - test
    environment:
      xcode: latest
      
  - name: Marathon Property Tests - Device 5
    platform: iOS
    runtime:
      version: '17.0'
      device: 'iPad mini (6th generation)'
    scheme: FaithQuest
    test-plan: Default
    test-repetitions: 20
    actions:
      - test
    environment:
      xcode: latest
